/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sp.naval;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import org.sp.resources.Imagenes;


public class JNaval extends javax.swing.JFrame {

    Image tablero;
    Image portada;
    int tableroMio[][]= new int[8][8];
    int tableroSuyo[][]=new int[8][8];
    int nEstado=0;
    Boolean primeraVez=true;
    
    
    
    
    
    public JNaval() {
        
        Imagenes i = new Imagenes();
        initComponents();
        portada = i.cargar("principal.jpg");
        tablero = i.cargar("tableroHundir.png");
        setBounds(0,0,800,600);
        addMouseListener(
        new MouseAdapter(){
        public void mouseClicked(MouseEvent e)
        {
            if(nEstado==0){
                nEstado=1;
                repaint();
            }
        }
        });
    }
    
    public boolean celdaEstaEnElTablero(int i, int j)
    {
        if(i<0)return false;
        if(j<0) return false;
        if(i>=8) return false;
        if(j>=8) return false;
        
        
    return true;
    }
    public Boolean puedePonerBarco(int[][] tab,int tam, int f, int c ,int hor){
        int df=0,dc=0;
        if(hor==1) df=1;
                else
            dc=1;
        
        for (int f2 = f-1; f2 < f+1; f2++) {
            for (int c2 = c; c2 < c+1+dc*tam; c2++) {
                
            }
        }
        return true;
    }
    
    public void ponerBarco(int[][] tab, int tam)
    { 
        int  f,c, hor;
        f= (int) (Math.random()*8);
        c= (int) (Math.random()*8);
        hor= (int) (Math.random()*2);
        do{}while(puedePonerBarco(tab,tam, f,c ,hor));
        
    }
    public void iniciarPartida()
    {
        
        
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                tableroMio[i][j]=0;
                tableroSuyo[i][j]=0;
            }
        }
        
        for (int tam = 0; tam <=5; tam++) {
            ponerBarco(tableroSuyo, tam);
        }
    }
    
    public void  paint(Graphics g) 
    {  
        if(primeraVez){ 
         g.drawImage(portada,0,0,this);
         g.drawImage(tablero,0,0,this);
         primeraVez=false;
      
        }
        
        if(nEstado==0){
          g.drawImage(portada,0,0,this);
        }else{
           pintarTablero(g,tableroMio,73,90);
           pintarTablero(g,tableroSuyo,485,90);
            iniciarPartida();
            g.drawImage(tablero,0,0,this);
         
        }
       
       
       
    }
    
    public void pintarTablero(Graphics g, int[][]tab,int x, int y)
    {
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j <8; j++) {
                if(tab[i][j]==0){
                    g.drawRect(x+i*30, y+j*30, 30, 30);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JNaval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JNaval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JNaval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JNaval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JNaval().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
